# Token of the personal Discord account that will mirror messages.
# Learn how to find your account token here: https://www.androidauthority.com/get-discord-token-3149920/
#token:

# Status of the account that will mirror messages.
# Available options: online, offline, idle, dnd.
#
# Note that you should not be logged into the account
# when the bot starts for this option to take effect.
status: "online"

# Message sent in the console when a message is mirrored.
# You can set this to "" to disable it.
logMessage: "[%date%] Mirrored @%author%'s message from %server% #%channel%."

mirrors:
   # The following contains a mirror with its options.
   # Every option is optional and can be removed from this file if not required.
   1:
      # You can find the id of a channel by enabling the Developer mode in your
      # Discord account settings and Right-Click -> Copy ID on a channel.
      channelIds:
         - "1166584390965530739"
      # Webhooks are used to send mirrored messages to specific channels.
      # You can create a webhook for a channel with:
      # Edit channel -> Integrations -> Webhooks -> New webook.
      webhookUrls:
         - "https://discord.com/api/webhooks/1197744864515862560/fgkLieRpP2dnjyNogyulA30SrxJIxEU3-Eo7hOij8loQSeDihgQ4MgU6-TjaINbZz2d5"
      ignoredUserIds:
         - "insert_user_id_not_to_mirror_here"
      ignoredRoleIds:
         - "insert_role_id_not_to_mirror_here"
      # Requirements that a message must meet to be mirrored.
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         # Whether to use the webhook's profile picture and name to mirror messages.
         useWebhookProfile: false
         # Whether to remove attachments before mirroring a message.
         removeAttachments: false
         # Whether to mirror messages coming from bots.
         mirrorMessagesFromBots: true
         # Whether to mirror messages that are replies to other messages.
         mirrorReplyMessages: true
         # Whether to mirror messages when they are edited.
         mirrorMessagesOnEdit: false
      # Replacements to perform before mirroring a message.
      # The where: option is used to specify which part of a message
      # should be replaced. The available options are:
      #
      # everywhere, message_content, embed_author, embed_author_url,
      # embed_author_icon_url, embed_title, embed_description, embed_url,
      # embed_field_name, embed_field_value, embed_image_url, embed_thumbnail_url
      # embed_footer, embed_footer_icon_url, embed_color.
      replacements:
         1:
            replace: "insert_text_to_replace_here"
            with: "insert_replaced_text_here"
            where: "everywhere"
         # To replace mentions of @roles, @users or #channels,
         # you have to replace their ids. For example:
         # 2:
         #    replace: "insert_role_id_to_replace_here"
         #    with: "insert_replaced_role_id_here"
         #    where: "everywhere"
         #
         # To replace everything with a specific text, you can use the wildcard (*):
         # 3:
         #    replace: "*"
         #    with: "this_text_will_replace_everything"
         #    where: "everywhere"
   # You can create as many mirrors as you want, so that different
   # channels can be mirrored to different webhooks. For example:
   # 2:
   #   channelIds:
   #     - "insert_channel_id_to_mirror_here"
   #   webhookUrls:
   #     - "insert_destionation_webhook_url_here"
   # Secured Picks
   2:
      channelIds:
         - "1097357434466611290"
      webhookUrls:
         - "https://discord.com/api/webhooks/1197745494567420072/A-8pMxa49EDOPeclWJ_pFQlkHpF6TOCp9KvC_U9lH_6KODwbu0Cs-bKxdp1xfnxflgvO"
      ignoredUserIds:
      ignoredRoleIds:
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
   # Cook the Books
   3:
      channelIds:
         - "1154517952318668850"
      webhookUrls:
         - "https://discord.com/api/webhooks/1197729661099196567/PqJkQhAiLHTTzNWqMn6t6FHdl9BrFrZkV0xbgD0kBs3giY4KNBFMeRtPieO6KRDCDr0z"
      ignoredUserIds:
      ignoredRoleIds:
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
   # Prize Picks Fiendz
   4:
      channelIds:
         - "1058854229227339846"
      webhookUrls:
         - "https://discord.com/api/webhooks/1197745604542091354/ZZxmwha1WLoZRppKwcFVxqbK9YyEQnX4KVzFDIrU7hkgrAiOyiv23x7UhLp5XYVYuxD1"
      ignoredUserIds:
      ignoredRoleIds:
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
      
