# Token of the personal Discord account that will mirror messages.
# Learn how to find your account token here: https://www.androidauthority.com/get-discord-token-3149920/
#token:

# Status of the account that will mirror messages.
# Available options: online, offline, idle, dnd.
#
# Note that you should not be logged into the account
# when the bot starts for this option to take effect.
status: "online"

# Message sent in the console when a message is mirrored.
# You can set this to "" to disable it.
logMessage: "[%date%] Mirrored @%author%'s message from %server% #%channel%."

mirrors:
   # The following contains a mirror with its options.
   # Every option is optional and can be removed from this file if not required.
   1:
      channelIds:
         - "1197986392471502991"
      webhookUrls:
         - "https://discord.com/api/webhooks/1197987122544660501/4NMYC6nr_-T-LvfgvDXnGVGh9gutvL-mVkTh7RFDNh1WiD-9v4RQZoLACiZlFf5W3-0x"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
   
