# Token of the personal Discord account that will mirror messages.
# Learn how to find your account token here: https://www.androidauthority.com/get-discord-token-3149920/
#token:

# Status of the account that will mirror messages.
# Available options: online, offline, idle, dnd.
#
# Note that you should not be logged into the account
# when the bot starts for this option to take effect.
status: "online"

# Message sent in the console when a message is mirrored.
# You can set this to "" to disable it.
logMessage: "[%date%] Mirrored @%author%'s message from %server% #%channel%."

mirrors:
   # The following contains a mirror with its options.
   # Every option is optional and can be removed from this file if not required.
   #Racha
   1:
      channelIds:
         - "951664031092047882"
      webhookUrls:
         - "https://discord.com/api/webhooks/1197987122544660501/4NMYC6nr_-T-LvfgvDXnGVGh9gutvL-mVkTh7RFDNh1WiD-9v4RQZoLACiZlFf5W3-0x"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "@everyone"
            with: "<@&1203561460328824842>"
            where: "everywhere"
   #Professor Picks   
   2:
      channelIds:
         - "1198355146208452609"
      webhookUrls:
         - "https://discord.com/api/webhooks/1203140496201879552/KdSm0Po8R0V3EnYW5NRlHDXN8czabkJxBDm4n_AZr0IU9e3Du2MHkunlE1P-YTXD3INB"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "@everyone"
            with: "<@&1203566449239785502>"
            where: "everywhere"
         2:
            replace: "<@&1109563652736045071>"
            with: ""
            where: "everywhere"
         3:
            replace: "<@&1109563837453189241>"
            with: ""
            where: "everywhere"
         4:
            replace: "<@&1198358782460317796>"
            with: ""
            where: "everywhere"      
   #cjay
   3:
      channelIds:
         - "1021665564688666705"
      webhookUrls:
         - "https://discord.com/api/webhooks/1203140941695942737/UCaMKY7cBA0UTcO7UNsjWZGfgQcVCZitkR-SlRqwxjpRipsgy6k9yJALpxrSCV22lzB-"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "1113487492528754748"
            with: "1203566515878891591"
            where: "everywhere"
   #matt   
   4:
      channelIds:
         - "1102049925904203796"
      webhookUrls:
         - "https://discord.com/api/webhooks/1203141215361568768/5R9vztKpteoZ28GupbrMI0NCGzBa3okTty1f60C_kWjdChd5gwMIwBynSXjT-NVc53ga"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "1102049925199568906"
            with: "1203570316471701524"
            where: "everywhere" 
      
   #greek   
   5:
      channelIds:
         - "1050913079380164628"
      webhookUrls:
         - "https://discord.com/api/webhooks/1203153058402406401/sBlbmZk9LAp1ZtFIX7BDf-WGv7SUb0LFJU6qds0ttZ5I84AOCqQQ7fflbFVDn6VgQow7"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "1050914872134729778"
            with: "1203570595758080031"
            where: "everywhere" 
   #zeke   
   6:
      channelIds:
         - "952774829646442496"
      webhookUrls:
         - "https://discord.com/api/webhooks/1203153393447600189/8q2WyGJM1CYtbbafgQsP-dBewtZmvRN8PjvIIMkMk8O-fV06GIhV5wZ2jxCHasDiOqtP"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "952781652063551580"
            with: "1203582412714418246"
            where: "everywhere"
         2:
            replace: "<@&1086063329455394927>"
            with: ""
            where: "everywhere"
#cjay
   7:
      channelIds:
         - "1199433351426224290"
      webhookUrls:
         - "https://discord.com/api/webhooks/1203881371987083267/H5E1DMHNrODpRsWzgEOZV_VV5KqsCJUqosYkXCfoRTjAmhNoo6mcjYdcCYIia5uWUH69"
      ignoredUserIds:
         - ""
      ignoredRoleIds:
         - ""
      requirements:
         minEmbedsCount: 0
         minContentLength: 0
         minAttachmentsCount: 0
      options:
         useWebhookProfile: false
         removeAttachments: false
         mirrorMessagesFromBots: true
         mirrorReplyMessages: true
         mirrorMessagesOnEdit: false
      replacements:
         1:
            replace: "1200237410672455780"
            with: "1203882126622072853"
            where: "everywhere"